[package]
name = "bevy_swash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.2"
swash = "0.1.17"
thiserror = "2.0.3"
